docs(python): Specify version upper bound
When trying to run this locally, I received an error [1]. It was moved
in Python 3.10 [2].

I've also added a new Makefile target to improve hints for what's
going wrong when running other targets. Along with this, I've
corrected some punctuation and whitespace.

[1]
```python
AttributeError: module 'collections' has no attribute 'Callable'
```
[2] https://docs.python.org/3/whatsnew/3.10.html#removed